fix: remove updatedAt query - column doesn't exist
Error: column "updatedAt" of relation "Order" does not exist

Removed unnecessary UPDATE query that was trying to set
updatedAt column which doesn't exist in the Order table.

This query wasn't needed - order was just created.